//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpDownLoad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileUpDownLoad.Resources.ConstantResources", typeof(ConstantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File feldolgozás.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A letöltendő file név üres!.
        /// </summary>
        internal static string EmptyFilename {
            get {
                return ResourceManager.GetString("EmptyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file már létezik a mappában.
        /// </summary>
        internal static string FileAllreadyExists {
            get {
                return ResourceManager.GetString("FileAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sikeresen letöltve!.
        /// </summary>
        internal static string FileDownloadSucceded {
            get {
                return ResourceManager.GetString("FileDownloadSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres feltöltés.
        /// </summary>
        internal static string FileUploadSucceded {
            get {
                return ResourceManager.GetString("FileUploadSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Célmappa nem létezik vagy üres.
        /// </summary>
        internal static string FolderNotExists {
            get {
                return ResourceManager.GetString("FolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs feltöltendő file kiválasztva.
        /// </summary>
        internal static string NoUploadFile {
            get {
                return ResourceManager.GetString("NoUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott file már létezik. Felülírjam?.
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Könyvtár tartalma.
        /// </summary>
        internal static string Tab1_Title {
            get {
                return ResourceManager.GetString("Tab1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File feltöltés.
        /// </summary>
        internal static string Tab2_Title {
            get {
                return ResourceManager.GetString("Tab2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File letöltés.
        /// </summary>
        internal static string Tab3_Title {
            get {
                return ResourceManager.GetString("Tab3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
